spring.datasource.url=jdbc:postgresql://admin:1xtvcCG5lb3qkYwx8LiB3fyLs7I5LAUt@dpg-d8dg136rnols739aohag-a/bibliotheque_db_rhxr
spring.datasource.username=admin
spring.datasource.password=TON_VRAI_MOT_DE_PASSE
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=MaCleSecreteTresLonguePourJWTToken2026BibliothequeUniversitaireUNZGroupe6Koudougou
app.jwt.expiration=86400000